version: '3'

services:
  centercore:
    build: .
    restart: always
    ports:
      - 80:8080
    env_file:
      - .env.docker
  
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres